#+title:  Virtual Labs Project ideas
#+SETUPFILE: ../org-templates/level-1.org


* MS projects
** Cloud Engineering for Virtual Labs  (MS: 1 student)
   The Virtual Labs project (http://www.vlabs.ac.in) is
   currently hosting more than a thousand experiments and
   has had more than 2 Million usages in 500 nodal centres
   across the country.  The Virtual labs are currently
   running from a commercial (AWS) cloud that costs us about
   1.5 Lakh rupees per month.

   The objective of this project is to carry out performance
   analysis and aggressive optimizations and
   re-architecturing to improve performance and bring down
   the costs by at least 50 percent.  The second part of the
   project coming up with an architecture that can run out
   of a desktop computer with modest (4-8GB) RAM serving
   about 50 students in a classroom.

** Automated renarration and curation for Virtual Labs (MS: 1 student)
   Renarration is a way of adapting web content for local
   contexts.  This project involves mining NPTEL content
   (about 16000+ hours of lectures) and virtual labs and
   creating an environment where appropriate learning
   resources are juxtaposed together to enhance the
   student's experience of learning.  The work will build on
   existing work already being done at SERC (with current
   PhD student Sai Gollapudi and current MS student MS
   Soumya).  The work may require working closely with the
   NPTEL team at IIT Madras.

** Analytics service for Virtual Labs  (MS: 1 student)
   The objective of this project is to design and develop a
   comprehensive virtual labs analytics service to be used
   by students and teachers.  


* BTech Projects

** Interaction Design for Virtual Labs (BTP/MS)

The objective of this project is to come up with a uniform
interface for interacting with virtual labs based on solid
interaction design and usability principles.  

** Searchable widget library for virtual labs (2 students)

   Effectively building experiments for Virtual Labs depends
   on having large libraries of widgets for each discipline.
   The objective of this project is to build a library of
   widgets and provide the library as a micro-service usable
   by a lab authoring environment.

** Threat model and security hardening of virtual labs project (1 student)
   The virtual labs are currently running a cluster of over
   a 100 VMs/Containers.  The objective of this project is
   to do security hardening of the virtual labs cluster and
   the experiments running from it.

** Lab Development Environment for Computer Science Virtual Labs  (2 students) 
   The aim here is to develop a browser based visual
   programming editor for building graph based computer
   science experiments, specially in data structures,
   algorithms, and programming language interpreters.

** Development of virtual labs experiments  using Augmented Reality/Virtual Reality (1 student)
The objective is to construct AR/VR experiments in
science/engineering or computing.  
