#+title: 2020 Summer Internship Positions
#+SETUPFILE: ../org-templates/level-1.org

* Duration of internship program
 
  =[2020-06-01 Mon]= and =[2020-07-31 Fri]=.  Longer
  internships of 6 months or more duration are also
  possible.  Please write to us at =jobs@vlabs.ac.in= if you
  are interested.


* Location  and Work schedule

  B-204, Vindhya C6, IIIT Hyderabad.  Work hours:
  Monday-Friday 9am-6pm.


* Project Listing 
 
  1. [[#project-details-one][Android Development]]

  2. [[#project-details-two][Responsive design]]

  3. [[#project-details-three][Developing backend infrastructure]]

  4. [[#project-details-four][Implementing SSO]]

  5. [[#project-details-five][Experiment Development Framework]]


* Benefits/Stipend

  * Certificate of participation at the end of internship
    and references from the mentors on a need basis.

  * This is an unpaid internship 


* Application Process

  Make sure you have your =github= handle and a resume
  available online.  Then fill the online application
  [[https://docs.google.com/forms/d/e/1FAIpQLSdjw5HR4AXQS1iOIj-9nCPshjMC333EJBtiXXuY8v9qdcza4w/viewform][=form=]].


* Application Deadline 

  25th May, 2020


* Project Details

We are looking for internship position for the following
projects.


** 1. Project Name - Android Development
 :PROPERTIES:
 :CUSTOM_ID: project-details-one
 :END:

  *Number of Positions - 1*

  *Project Description*

  Virtual Labs Engineering and Architecture Division (VLEAD)
  is looking for competent and experienced Android
  developers to work on building a state of the art Android
  app for Virtual Labs. We are looking for a developer who
  can build high-quality applications in compliance with
  standards, quality guidelines and relevant best practices.
  
  *Project Requirements*
   
    - Small network footprint. Our data is fairly static and
      most of it can be cached on the client device.
  
    - Low processing overhead. App should run smooth on a
      mid/low range phone at 3G network speeds
  
    - Intuitive. App use and navigation should be easy to
      follow for a user with moderate technical savvy.

  *Role Requirements*
 
   You are expected to have a good understanding of the following:

    - Latest Android SDK

    - REST API integration with Android Apps

    - Latest Android design patterns and best practices

    - Android app performance tuning

   Knowledge of the following will be a plus:

    - Analytics frameworks for Android apps


** 2. Intern for Responsive design
 :PROPERTIES:
 :CUSTOM_ID: project-details-two
 :END:

  *Number of Positions - 1*

  *Project Description* 

   Virtual Labs Engineering and Architecture Division
   (VLEAD) is looking for competent and experienced frontend
   web developer to work on building a contemporary,
   responsive UI for Virtual Labs. We are looking for a web
   developer who can build high-quality UI components in
   compliance with standards, quality guidelines and
   relevant best practices.

   You are expected to have a good understanding of the
   following:
     - CSS3

     - SCSS (all the code will be written in SCSS and
       compiled to CSS)

     - Flexbox/CSS Grid

   Knowledge of the following will be a plus:

    - Webpack
 
    - npm

    - Material design

  Following are the requirements of the UI:

    - It should be super-light. We are not looking to use
      any libraries larger than 5KB, bundled and gzipped.

    - Low processing overhead. App should run smooth on a
      mid/low range phone at 3G network speeds.

    - Intuitive. UI use and navigation should be easy to
      follow for a user with moderate technical savvy.









** 3. Project Name - developing backend infrastructure
 :PROPERTIES:
 :CUSTOM_ID: project-details-three
 :END:


   *Number of Positions - 2*
 
   *Project Description*

   Virtual Labs Engineering and Architecture Division
   (VLEAD) is looking for competent and experienced
   application developer to work on developing the backend
   instrastructure for Virtual Labs. You will be required to
   work on creating a Kubernetes based service stack
   alongwith the platform services like logging, monitoring,
   and analytics. You may also have to work on implementing
   a few auto-scaled, self-managed, cloud-based core
   micro-services. We are looking for developers who can
   build high-quality backend modules in compliance with
   standards, quality guidelines and relevant best
   practices.


   *Role Requirements*

    You are expected to have a good understanding of the
    following:

     - Micro-service architecture and patterns
     
     - Docker
     
     - Kubernetes
     
     - Python/Nodejs
 
   Knowledge of the following will be a plus:
   
     - Prometheus
     
     - AWS EKS


** 4. Project Name - implementing SSO
 :PROPERTIES:
 :CUSTOM_ID: project-details-four
 :END:

   *Number of Positions - 1*

   *Project Description*

   Virtual Labs Engineering and Architecture Division
   (VLEAD) is looking for competent and experienced
   application developer to work on developing the Single
   Sign On instrastructure for Virtual Labs. You will work
   on integrating Virtual Labs with multiple Identity
   Providers including Google, Swayam, Twitter and
   Facebook. In some case you will have to work with the
   Identity Providers representatives. We are looking for
   developers who can build high-quality software systems in
   compliance with standards, quality guidelines and
   relevant best practices.

   *Role Requirements*

   You are expected to have a good understanding of the
   following:

     - State of the art Authentication protocols (OpenID
       Connect, SAML)

     - Web Server Configuration (Apache httpd preferred)

     - HTTP

   Knowledge of the following would be a plus:
    
     - Identity provider integration

     - Basic web development concepts


** 5. Project Name - Experiment Development Framework
 :PROPERTIES:
 :CUSTOM_ID: project-details-five
 :END:

   *Number of Positions - 3*

   *Project Description*

   Virtual Labs Engineering and Architecture Division (VLEAD) is
   looking for competent and experienced application developer to work
   on the experiment development framework for Virtual Labs. You will
   be working on developing an architecture for building virtual labs
   experiments and a set of tools to help developers build better
   experiments. These tools in the form of libraries, will be a part
   of an experiment development framework, which is targeted towards
   delivering experiments in the form of scalable web applications. You
   will also be developing some computer science experiments using the
   same tools we build.  As part of this project, you will be
   working with the Elm framework for web application development.  We
   are looking for developers who have good knowledge of computer
   science concepts and are capable of developing high quality
   software that can be published as an open source package.

   *Role Requirements*

   You are expected to have a good understanding of the
   following:

     - Basics of Computer Science (Data Structures, Algorithms)

     - Basics of web application development (HTML, JavaScript, css)

     - Any popular web framework (React, Vue, Angular, Elm etc.)

     - Web Graphics Technologies

     - Functional Programming

   Knowledge of the following would be a plus:

     - Elm Programming Language

     - Literate Programming with Org-mode




* Questions

  Please email =2020-summer-interns@vlabs.ac.in=.



