#+title: Frontend Web Developer
#+SETUPFILE: ../org-templates/level-1.org

* Job Description

Virtual Labs Engineering and Architecture Division (VLEAD) is looking
for competent and experienced frontend web developers to work in the
core technologies of Virtual Labs. You will be part of a talented team
of engineers that demonstrates superb technical competency for
ensuring highest levels of performance and availability of critical
infrastructure. The engineering team at Virtual Labs is looking at
innovative ways to design, develop and deploy the various applications
with high uptime requirements. We are looking for developers who can
build high-quality frontend modules in compliance with standards,
quality guidelines and relevant best practices. Commonly used
technologies for Virtual Labs are:

- OS: Linux/Unix

- Tools: Redmine (Project Management System), Mediawiki, Emacs (Org-mode)

- Version control: git

Some of the problems that you can solve as part of the
team:

- Find solutions to complex issues that are unique to our project and
  integrate them across integration teams.

- Build low-latency systems and make data-driven decisions.

- Build intelligent platforms that maximize the value of our
  offering and helps us proactively reach out to more customers.

We need someone who has good programming experience in HTML, CSS and
Javascript. An in-depth understanding of web aesthetics would be
appreciated. Our technology stack is primarily Python with HTML, CSS
and Javascript on the frontend and a MySql, Jquery backend. We are
looking at someone who has interest in functional programming,
Haskell, Scheme and Scala. We follow a technology agnostic approach
and adopt the best technology for solving the problem at hand. We have
a bias towards action, creative problem solving and a metrics driven
mindset. We are a fully open source shop and big believers in
contributing back to the community.

** Role

- Frontend module development, design and implemention of new features
  and functionalities. Creating responsive designs and rendering it
  into a working theme.
- Work closely with back-end developers and customers to ensure an
  effective, visually appealing, and intuitive implementation.
- Move to state-of-the-art technologies as demanded by the environment
  and ensure effective delivery of outcomes.

** Requirements

- B.Tech or higher in Computer Science or equivalent.
- 3+ years of relevant frontend web development experience is
  desirable.
- Fluent with HTML5/XHTML, CSS and Javascript.
- Cognizance with REST APIs and service-oriented-architecture (SOA).
- Experience in functional programming, Haskell, Scheme and Scala 
  languages would be appreciated.
- Solid foundation in computer science principles with good
  requirements and design documentation skills.
- Good problem solving skills with curiosity to explore technology.
- Quick self learner, proactive team player and an effective
  communicator.
- In depth understanding of the entire web development process
  including design, development and deployment with some back-end
  knowledge would be desirable.

Please apply at jobs@vlabs.ac.in

