#+title: Technical Project Manager
#+SETUPFILE: ../org-templates/level-1.org

* Job Description

Virtual Labs Engineering and Architecture Division (VLEAD) is looking
for a competent and experienced technical project manager to work in
the core technologies of Virtual Labs. The engineering team is looking
for a technical architect who can conceptualize and design intelligent
systems, understand the project ecosystem, identify issues and
bottlenecks and proactively come up with solutions. Commonly used
technologies for Virtual Labs are:

- OS: Linux/Unix

- Tools: Redmine (Project Management System), Mediawiki, Emacs (Org-mode)

- Version control: git

Some of the problems that you can solve while managing different teams:

- Find solutions to complex issues that are unique to our project and
  integrate them across integration teams.

- Conceptualise and build intelligent platforms that maximize the
  value of our offering and helps us proactively reach out to more
  customers.

We need someone who has good experience in Linux Operating Systems,
object-oriented programming, JavaScript, jQuery, Database knowledge,
and web services. Our technology stack is primarily Python with a
MySql backend, Javascript, JQuery, HTML, CSS on the frontend. We are
looking at someone who has interest in functional programming,
Haskell, Scheme and Scala. We follow a technology agnostic approach
and adopt the best technology for solving the problem at hand. We have
a bias towards action, creative problem solving and a metrics driven
mindset. We are a fully open source shop and big believers in
contributing back to the community. If building open source IT stacks
excites you, then our team might be your next career step.

** Role

- Drive architecture discussions, code reviews, design reviews and
  inculcate engineering best practices across the team. Be part of
  annual external review meetings at MHRD.
- Strong emphasis on performance and quality with a sharp business
  sense.
- Be an advocate for an extensible, scalable and maintainable design
  and lead by example.
- Drive long term technology initiatives.
- Be a technical mentor for team members and drive improvements in
  coding standards across large code bases.
- Move to state-of-the-art technologies as demanded by the environment
  and ensure effective delivery of outcomes.

** Requirements

- B.Tech or higher in Computer Science or equivalent.
- 7+ years of relevant software design and development experience is
  desirable.
- Solid coding and problem solving skills with ability to architect
  cross team features to refactoring existing frameworks.
- Exposure to a wide range of problem spaces and technologies and the
  ability to evaluate upcoming technologies.Good understanding of
  SDLC, and the Program Management methods.
- Experience in functional programming, Haskell, Scheme and Scala 
  languages would be appreciated.
- Solid foundation in computer science principles with good
  requirements and design documentation skills.
- Ability to create strong working relationships within and across
  functional teams.
- Deep understanding of distributed systems and familiarity with
  design patterns.
- LAMP stack proficiency (Expertise with Python is preferred.)
- Prior startup experience (cloud-based product or service is a
  bonus), AWS experience and contributions to open source projects
  would be desirable.

Please apply at jobs@vlabs.ac.in

