#+title: Directory of GitHub Repositories
#+SETUPFILE: org-templates/level-0.org

All the Virtual Lab Development projects are on [[http://github.com/][GitHub]].

* Platform and Services Repositories

All the repositories are under the organization [[http://github.com/vlead][vlead]]. 

A sampling of repositories dealing with the development of Platform and
Services are

** Auto Deployment Service

   This [[http://github.com/vlead/ovpl][service]] transforms a github url of a web application to hosted url. 
   
** dataservice
   
   This [[http://github.com/vlead/dataservice][service]] is the central data store that provides a REST API to perform
   CRUD operations on the data. 

** Outreach Portal

   This [[http://github.com/vlead/outreach-portal][portal]] helps in facilitating conducting workshops.  These workshops
   allow the engineering students to see the value in virtual labs.

** Virtual Labs Landing Page
   
   [[https://github.com/vlead/vlab-web-pages][Virtual Labs landing page]] is the home page of virtual labs which lists all
   the available labs. 


* Virtual Labs

  All the repositories are under the organization [[http://github.com/Virtual-Labs][Virtual-Labs]]. 

  Few of the sample labs are:
  
** Computer Programming
   A [[https://github.com/Virtual-Labs/computer-programming-responsive-iiith][Lab]] that explores programming
 
** Data Structures
   A [[https://github.com/Virtual-Labs/data-structures-iiith][Lab]] that explains data structures using simulations.
