#+title:  Introduction to Virtual Labs Developmnet Portal
#+SETUPFILE: org-templates/level-0.org

This is a one stop pit shop to find resources to enable users to connect and
contribute towards either development of the platform and services that
facilitate deployment of labs or towards the development of virtual labs.

* Getting Started
  An overview of virtual labs development is provided here along with
  information on connecting with people for getting help. 

* Features
  This section provides information on various projects related to either
  building services, platforms, portals, etc.

* Lab Development
  This section contains all the related information for virtual lab
  development. 

* Contributing
  In this section, all learn about standards and processes for contributing
  code virtual labs development.

* Community
  All the necessary information on how to connect with people using different
  channels to understand and contribute to virtual labs development is provided
  here.







