* Job Title: Systems Engineer
** Number of positions : 01
Virtual Labs Engineering and Architecture Division (VLEAD) is looking
for competent and experienced systems engineers to work in the core
technologies of Virtual Labs. You will be part of a talented team of
engineers that demonstrates superb technical competency for ensuring
highest levels of availability, performance and security of critical
infrastructure. The engineering team at Virtual Labs is looking at
innovative ways to automate and manage the infrastructure with high
uptime requirements. We are looking for a systems engineer who can
build high-quality and fully performing infrastructure systems in
compliance with standards, quality guidelines and relevant best
practices. Commonly used technologies for Virtual Labs are:

- OS: Linux/Unix, specifically CentOS

- Servers: Apache web server, BIND DNS, OpenLDAP

- Tools: iptables, Mediawiki, Emacs (Org-mode)

- Version control: git

- Configuration management: Ansible

- Virtualization: Container or OS level virtualization with OpenVZ

Some of the problems that you can solve as part of the
team:

- Automate infrastructure including apache web server, reverse proxy,
  Bind DNS, SSH, etc. using ansible for a cluster of 100+
  nodes.

- Manage Amazon Web Services (AWS) Virtual Machines (VMs)
  cluster of 100+ VMs remotely.

- Find solutions to complex issues that are unique to our project and
  integrate them across integration teams.

- To make data-driven decisions in real-time or minimal latency.

- Build intelligent platforms that maximizes the value of our
  offering and helps us proactively reach out to more customers.

We are a fully open source shop and big believers in contributing back
to the community. If building open source cloud solutions from scratch
excites you, then our team might be your next career step.

** Role

- Installation, configuration, test and maintenance of application
  software, servers and operating systems with configuration
  management tools.
- Building, maintaining, troubleshooting and scaling our rapidly
  expanding infrastructure.
- Use of versioning for both documentation and configuration
  management.
- Proactively ensuring availability and security of IT infrastructure.
 

** Requirements

- B.Tech or higher in Computer Science or equivalent required.
- 3+ years of relevant server and network infrastructure operations
  experience is desirable. Hands on experience in automating
  infrastructure.
- Understanding of basic networking:: IP addresses, Firewalls, basic
  protocols. Demonstration of understanding in Linux security.
- Problem solving skills, curiosity to explore technology, quick self
  learner, passionate, proactive, and a good communicator.
- Be a great team player and able to work with all the stake holders. 
- Be able to document requirements and specifications.
- Programming and scripting skills (e.g., shell scripts) and
  experience in OS and other applications would be desirable.

Post your details at [[jobs@vlabs.ac.in]]
